import type { ResumeData, SuggestedQuestion } from "@/types";

export const resumeData: ResumeData = {
  name: "Damilola Elegbede",
  title: "Distinguished Engineer — AI Systems & Infrastructure",
  tagline:
    "I architect multi-agent AI systems and the platform primitives that make them reliable, observable, and fast.",
  brandingStatement:
    "Strategic engineering leader with 15+ years scaling mission-critical infrastructure at Verily Life Sciences and Qualcomm. Designed a cloud transformation supporting 30+ production systems, enabling flagship product launches (L'Oréal LDP, T1D). Expert at building high-performance teams, driving GCP/AWS migrations, and establishing platform engineering practices that improve developer velocity and system reliability.",
  email: "damilola.elegbede@gmail.com",
  linkedin: "https://linkedin.com/in/damilola-elegbede/",
  github: "https://github.com/damilola-elegbede",
  location: "Boulder, CO",
  openToRoles: [
    "Distinguished Engineer",
    "Principal Engineer",
    "Staff Engineer",
    "Engineering Director",
  ],
  experienceTags: [
    "Multi-Agent Systems",
    "AI Infrastructure",
    "Platform Engineering",
    "Distributed Systems",
    "Engineering Leadership",
    "MBA + MS CS",
  ],
  experiences: [
    {
      id: "verily",
      company: "Verily Life Sciences",
      title:
        "Engineering Manager - Cloud Infrastructure & Developer Experience",
      location: "Boulder, CO",
      startDate: "Sep 2022",
      endDate: "Nov 2024",
      highlights: [
        "Built the cloud infrastructure platform (GCP, CI/CD, developer tooling) that became the foundation for Verily's AI/ML workload migration — scaled platform to support 200+ engineers while cutting CI cycle time by 40%.",
        "Architected and executed enterprise-wide GCP cloud transformation supporting 30+ production systems, enabling successful launches of L'Oréal LDP and T1D healthcare platforms while establishing multi-cloud (GCP/AWS) capabilities.",
        "Built Cloud Infrastructure and developer experience functions from ground up, hiring and scaling an engineering team across multiple requisition cycles; promoted 3 ICs to senior roles, achieved high team retention with multiple internal transfers to the organization.",
        "Drove platform efficiency initiatives with significant CI efficiency improvement and establishing self-service infrastructure capabilities, improving developer velocity across a large engineering organization.",
        "Led executive stakeholder alignment across Engineering, Product, and Security organizations, influencing enterprise-wide policies on containerization, observability, and cloud architecture adopted by 15+ teams.",
        "Delivered complex multi-phase production launches including T1D platform (20+ systems, 5 deployment phases), managing cross-functional dependencies and security compliance requirements.",
        "Established Cumulus Office Hours support model and SLA framework, transforming infrastructure support from reactive to proactive while maintaining sub-4-hour resolution times for critical issues.",
      ],
    },
    {
      id: "qualcomm-staff-manager",
      company: "Qualcomm Technologies",
      title: "Engineer, Senior Staff/Manager",
      location: "Boulder, CO",
      startDate: "Oct 2019",
      endDate: "Jul 2022",
      highlights: [
        "Led infrastructure engineering for 4G/5G CI/CD at Qualcomm, establishing platform patterns for distributed build systems at scale — the same architectural discipline applied to modern AI training and inference pipelines.",
        "Transformed customer support operations from reactive to proactive model, dramatically reducing critical issue resolution time while scaling to support a large global customer deployment base.",
        "Created self-service 5G training platform replacing quarterly live sessions, enabling 24/7 customer enablement across global time zones and significantly reducing training operational costs.",
        "Led data-driven performance optimization using Splunk analytics, identifying and resolving signal-to-noise ratio issues across 40+ customer sites, directly improving chipset performance metrics.",
        "Established Release Engineering function compressing multi-day software deployment cycles to same-day delivery, accelerating time-to-market for critical 5G features.",
      ],
    },
    {
      id: "qualcomm-staff",
      company: "Qualcomm Technologies",
      title: "Engineer, Staff/Manager",
      location: "Boulder, CO",
      startDate: "Oct 2014",
      endDate: "Oct 2019",
      highlights: [
        "Delivered multiple major 4G feature releases annually while maintaining high platform stability, directly supporting Qualcomm's telecom infrastructure revenue stream.",
        "Implemented CI/CD transformation with substantial build time reduction, improving productivity for a large engineering team and accelerating feature delivery.",
        "Led Agile transformation with measurable productivity improvement, implementing Scrum for development teams and Kanban for customer support operations.",
      ],
    },
    {
      id: "qualcomm-senior",
      company: "Qualcomm Technologies",
      title: "Senior Engineer",
      location: "Boulder, CO",
      startDate: "Oct 2009",
      endDate: "Oct 2014",
      highlights: [
        "Drove significant productivity improvement through Scrum implementation, enabling faster feature delivery for 3G roadmap across a large base station fleet.",
        "Streamlined customer support operations using Kanban methodology, meaningfully improving response times for a high volume of monthly customer tickets.",
      ],
    },
    {
      id: "qualcomm-engineer",
      company: "Qualcomm Technologies",
      title: "Engineer",
      location: "Boulder, CO",
      startDate: "Aug 2002",
      endDate: "Oct 2009",
      highlights: [
        "Developed core system components (Authentication, SMS, HSDPA, MIMO) supporting Qualcomm's 3G product roadmap.",
        "Demonstrated advanced wireless capabilities at global venues (CTIA Las Vegas 2008, FutureCom São Paulo 2009), directly supporting business development efforts.",
      ],
    },
  ],
  skills: [
    {
      category: "AI & Agent Systems",
      items: [
        "Multi-agent system design",
        "LLM infrastructure & prompt engineering",
        "Agent orchestration (Claude SDK, MCP protocol)",
        "AI observability (semantic event streaming, activity logging)",
        "Autonomous workflow scheduling (launchd, cron)",
        "Agent identity & credential management",
      ],
    },
    {
      category: "Leadership",
      items: [
        "Cross-Functional Leadership",
        "Technical Strategy",
        "Executive Stakeholder Management",
        "Multi-Site Team Leadership",
        "Agile/Scrum/Kanban",
        "Organizational Transformation",
      ],
    },
    {
      category: "Cloud & Infrastructure",
      items: [
        "Google Cloud Platform (GCP)",
        "AWS",
        "Multi-Cloud Architecture",
        "Kubernetes/GKE",
        "Docker",
        "Terraform",
        "Infrastructure as Code",
      ],
    },
    {
      category: "Developer Experience",
      items: [
        "CI/CD Pipeline Design",
        "GitHub Actions",
        "Jenkins",
        "Platform Engineering",
        "Release Engineering",
        "DevOps Practices",
        "SRE Principles",
      ],
    },
    {
      category: "Technical",
      items: [
        "Distributed Systems",
        "Microservices",
        "System Software",
        "Performance Optimization",
        "High Availability (99.99% uptime)",
        "Observability & Monitoring",
      ],
    },
    {
      category: "Programming",
      items: [
        "Python",
        "C++",
        "Go",
        "Java",
        "JavaScript/TypeScript",
        "Bash",
        "SQL",
      ],
    },
    {
      category: "Domain",
      items: [
        "Healthcare Technology",
        "Telecom Systems (5G/4G/3G)",
        "Enterprise Cloud Migration",
        "Regulatory Compliance",
      ],
    },
  ],
  skillsAssessment: {
    expert: [
      "Multi-agent system design",
      "Agent orchestration",
      "LLM infrastructure",
      "Prompt engineering at scale",
      "Cross-Functional Leadership",
      "Technical Strategy",
      "Executive Stakeholder Management",
      "Multi-Site Team Leadership",
      "Agile/Scrum/Kanban",
      "Organizational Transformation",
      "CI/CD Pipeline Design",
      "Jenkins",
      "Incident Management",
      "Mentoring/Coaching",
      "Training Development",
    ],
    proficient: [
      "MCP protocol",
      "AI observability",
      "Autonomous scheduling",
      "GitHub App identity management",
      "Claude SDK",
      "GCP",
      "Kubernetes/GKE",
      "Terraform",
      "Platform Engineering",
      "Distributed Systems",
      "SRE Principles",
      "Telecom Systems (5G/4G/3G)",
      "Python",
      "3GPP Standards",
      "RRC/L3 Layer",
      "FHIR",
      "gRPC",
      "Cloud Run",
      "BigQuery",
      "OpenTelemetry",
      "WebSockets",
      "JWT",
      "Knowledge Transfer",
      "JavaScript/TypeScript",
    ],
    familiar: [
      "AWS",
      "SQL",
      "YAML",
      "ArgoCD",
      "Atlantis",
      "Skaffold",
      "Cloud Deploy",
    ],
  },
  education: [
    {
      id: "mba",
      degree: "MBA",
      institution: "University of Colorado, Leeds School of Business",
    },
    {
      id: "ms",
      degree: "MS Computer Science",
      institution: "University of Colorado Boulder",
    },
    {
      id: "bs",
      degree: "BS Electrical & Computer Engineering / Computer Science",
      institution: "University of Wisconsin-Madison",
    },
  ],
};

export const suggestedQuestions: SuggestedQuestion[] = [
  {
    label: "Leadership Philosophy",
    question: "What's your leadership philosophy?",
  },
  {
    label: "Developer Growth",
    question: "How do you develop engineers into senior roles?",
  },
  {
    label: "Scaling Teams",
    question: "Tell me about a time you scaled a team?",
  },
  {
    label: "Conflict Resolution",
    question: "How do you handle team conflict?",
  },
  {
    label: "Technical Debt",
    question: "What's your approach to technical debt vs features?",
  },
];
