import type { ResumeData, SuggestedQuestion } from '@/types';

export const resumeData: ResumeData = {
  name: 'Damilola Elegbede',
  title: 'Engineering Manager',
  tagline:
    'Building high-performance organizations that deliver enterprise-scale solutions',
  brandingStatement:
    "Strategic engineering leader with 15+ years scaling mission-critical infrastructure at Verily Life Sciences and Qualcomm. Designed a cloud transformation supporting 30+ production systems, enabling flagship product launches (L'Oréal LDP, T1D). Expert at building high-performance teams, driving GCP/AWS migrations, and establishing platform engineering practices that improve developer velocity and system reliability.",
  email: 'damilola.elegbede@gmail.com',
  linkedin: 'https://linkedin.com/in/damilola-elegbede/',
  github: 'https://github.com/damilola-elegbede',
  location: 'Boulder, CO',
  openToRoles: ['Engineering Manager', 'Senior Engineering Manager'],
  experienceTags: ['Ex-Verily', 'Ex-Qualcomm', 'MBA + MS CS'],
  experiences: [
    {
      id: 'verily',
      company: 'Verily Life Sciences',
      title: 'Engineering Manager - Cloud Infrastructure & Developer Experience',
      location: 'Boulder, CO',
      startDate: 'Sep 2022',
      endDate: 'Nov 2024',
      highlights: [
        "Architected and executed enterprise-wide GCP cloud transformation supporting 30+ production systems, enabling successful launches of L'Oréal LDP and T1D healthcare platforms while establishing multi-cloud (AWS/GCP) capabilities.",
        'Built Cloud Infrastructure and developer experience functions from ground up, hiring and scaling to 13 engineers across 4 req cycles; promoted 3 ICs to senior roles, achieved 93% retention with multiple internal transfers to my org.',
        'Drove platform efficiency initiatives reducing GitHub Actions usage by 30% and establishing self-service infrastructure capabilities, improving developer velocity across 400+ engineers.',
        'Led executive stakeholder alignment across Engineering, Product, and Security organizations, influencing enterprise-wide policies on containerization, observability, and cloud architecture adopted by 15+ teams.',
        'Delivered complex multi-phase production launches including T1D platform (20+ systems, 5 deployment phases), managing cross-functional dependencies and security compliance requirements.',
        'Established Cumulus Office Hours support model and SLA framework, transforming infrastructure support from reactive to proactive while maintaining sub-4-hour resolution times for critical issues.',
      ],
    },
    {
      id: 'qualcomm-staff-manager',
      company: 'Qualcomm Technologies',
      title: 'Engineer, Senior Staff/Manager',
      location: 'Boulder, CO',
      startDate: 'Oct 2019',
      endDate: 'Jul 2022',
      highlights: [
        'Transformed customer support operations from reactive to proactive model, reducing critical issue resolution time by 75% while scaling to support 400+ customer deployments globally.',
        'Created self-service 5G training platform replacing quarterly live sessions, enabling 24/7 customer enablement across global time zones and reducing training operational costs by 60%.',
        'Led data-driven performance optimization using Splunk analytics, identifying and resolving signal-to-noise ratio issues across 40+ customer sites, directly improving chipset performance metrics.',
        'Established Release Engineering function compressing multi-day software deployment cycles to same-day delivery, accelerating time-to-market for critical 5G features.',
      ],
    },
    {
      id: 'qualcomm-staff',
      company: 'Qualcomm Technologies',
      title: 'Engineer, Staff/Manager',
      location: 'Boulder, CO',
      startDate: 'Oct 2014',
      endDate: 'Oct 2019',
      highlights: [
        "Delivered 6 major 4G feature releases annually while maintaining 99.9% platform stability, directly supporting Qualcomm's telecom infrastructure revenue stream.",
        'Implemented CI/CD transformation reducing build times by 87% (4 hours to 30 minutes), improving productivity for 100+ engineers and accelerating feature delivery.',
        'Led Agile transformation achieving 40% productivity improvement, implementing Scrum for development teams and Kanban for customer support operations.',
      ],
    },
    {
      id: 'qualcomm-senior',
      company: 'Qualcomm Technologies',
      title: 'Senior Engineer',
      location: 'Boulder, CO',
      startDate: 'Oct 2009',
      endDate: 'Oct 2014',
      highlights: [
        'Drove 40% productivity improvement through Scrum implementation, enabling faster feature delivery for 3G roadmap on ~300 Base Stations.',
        'Streamlined customer support operations using Kanban methodology, improving response times for ~100 monthly customer tickets by 50%.',
      ],
    },
    {
      id: 'qualcomm-engineer',
      company: 'Qualcomm Technologies',
      title: 'Engineer',
      location: 'Boulder, CO',
      startDate: 'Aug 2002',
      endDate: 'Oct 2009',
      highlights: [
        "Developed core system components (Authentication, SMS, HSDPA, MIMO) supporting Qualcomm's 3G product roadmap.",
        'Demonstrated advanced wireless capabilities at global venues (CTIA Las Vegas 2008, FutureCom São Paulo 2009), directly supporting business development efforts.',
      ],
    },
  ],
  skills: [
    {
      category: 'Leadership',
      items: [
        'Cross-Functional Leadership',
        'Technical Strategy',
        'Executive Stakeholder Management',
        'Multi-Site Team Leadership (35+ engineers)',
        'Agile/Scrum/Kanban',
        'Organizational Transformation',
      ],
    },
    {
      category: 'Cloud & Infrastructure',
      items: [
        'Google Cloud Platform (GCP)',
        'AWS',
        'Multi-Cloud Architecture',
        'Kubernetes/GKE',
        'Docker',
        'Terraform',
        'Infrastructure as Code',
      ],
    },
    {
      category: 'Developer Experience',
      items: [
        'CI/CD Pipeline Design',
        'GitHub Actions',
        'Jenkins',
        'Platform Engineering',
        'Release Engineering',
        'DevOps Practices',
        'SRE Principles',
      ],
    },
    {
      category: 'Technical',
      items: [
        'Distributed Systems',
        'Microservices',
        'System Software',
        'Performance Optimization',
        'High Availability (99.99% uptime)',
        'Observability & Monitoring',
      ],
    },
    {
      category: 'Programming',
      items: ['Python', 'C++', 'Go', 'Java', 'Bash', 'SQL'],
    },
    {
      category: 'Domain',
      items: [
        'Healthcare Technology',
        'Telecom Systems (5G/4G/3G)',
        'Enterprise Cloud Migration',
        'Regulatory Compliance',
      ],
    },
  ],
  skillsAssessment: {
    expert: [
      'Cross-Functional Leadership',
      'Technical Strategy',
      'Executive Stakeholder Management',
      'Multi-Site Team Leadership',
      'Agile/Scrum/Kanban',
      'Organizational Transformation',
      'Cross-Team Integration',
      'Enterprise System Migration',
      'JIRA',
      'Confluence',
    ],
    proficient: [
      'GCP',
      'Multi-Cloud Architecture',
      'Kubernetes/GKE',
      'Docker',
      'Terraform',
      'Infrastructure as Code',
      'Service Mesh (ASM)',
      'Platform Engineering',
      'Distributed Systems',
      'Microservices',
      'System Software',
      'Performance Optimization',
      'High Availability',
      'Observability & Monitoring',
      'API Design',
      'Container Orchestration',
      'CI/CD Pipeline Design',
      'GitHub Actions',
      'Jenkins',
      'Monorepo Management',
      'Release Engineering',
      'DevOps Practices',
      'SRE Principles',
      'Platform-as-a-Service',
      'Python',
      'C++',
      'Java',
      'Bash',
      'Splunk',
      'Data-Driven Decision Making',
      'Healthcare Technology',
      'Telecom Systems (5G/4G/3G)',
      'Enterprise Cloud Migration',
      'Regulatory Compliance',
      'Cross-Platform Development',
    ],
    familiar: ['AWS', 'SQL', 'YAML', 'Go'],
  },
  education: [
    {
      id: 'mba',
      degree: 'MBA',
      institution: 'University of Colorado, Leeds School of Business',
    },
    {
      id: 'ms',
      degree: 'MS Computer Science',
      institution: 'University of Colorado Boulder',
    },
    {
      id: 'bs',
      degree: 'BS Electrical & Computer Engineering / Computer Science',
      institution: 'University of Wisconsin-Madison',
    },
  ],
};

export const suggestedQuestions: SuggestedQuestion[] = [
  {
    label: 'Leadership Philosophy',
    question: "What's your leadership philosophy?",
  },
  {
    label: 'Developer Growth',
    question: 'How do you develop engineers into senior roles?',
  },
  {
    label: 'Scaling Teams',
    question: 'Tell me about a time you scaled a team',
  },
  {
    label: 'Conflict Resolution',
    question: 'How do you handle team conflict?',
  },
  {
    label: 'Technical Debt',
    question: "What's your approach to technical debt vs features?",
  },
];
