/**
 * Integration tests for chat session ID contract between frontend and backend
 *
 * These tests verify that the session ID format generated by the frontend
 * (chat-storage.ts) is accepted by all backend endpoints.
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';

// Mock @vercel/blob for archive tests
const mockPut = vi.fn();
vi.mock('@vercel/blob', () => ({
  put: mockPut,
}));

describe('chat session ID contract', () => {
  const SESSION_ID_PATTERN = /^chat-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

  beforeEach(() => {
    vi.clearAllMocks();
    vi.resetModules();
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  describe('frontend session ID generation', () => {
    it('initializeSession generates chat-prefixed UUID', async () => {
      // Mock localStorage
      const storage = new Map<string, string>();
      const localStorageMock = {
        getItem: vi.fn((key: string) => storage.get(key) ?? null),
        setItem: vi.fn((key: string, value: string) => storage.set(key, value)),
        removeItem: vi.fn((key: string) => storage.delete(key)),
      };
      Object.defineProperty(global, 'localStorage', { value: localStorageMock, writable: true });

      // Mock crypto.randomUUID
      const mockUUID = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890';
      Object.defineProperty(global, 'crypto', {
        value: { randomUUID: vi.fn().mockReturnValue(mockUUID) },
        writable: true,
      });

      const { initializeSession } = await import('@/lib/chat-storage');

      const sessionId = initializeSession();

      expect(sessionId).toBe(`chat-${mockUUID}`);
      expect(SESSION_ID_PATTERN.test(sessionId)).toBe(true);
    });
  });

  describe('backend validation accepts frontend format', () => {
    it('/api/chat validates chat-prefixed session ID correctly', async () => {
      // The regex used in /api/chat/route.ts
      const backendPattern = /^chat-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

      // Sample session IDs that frontend generates
      const validSessionIds = [
        'chat-a1b2c3d4-e5f6-7890-abcd-ef1234567890',
        'chat-12345678-1234-1234-1234-123456789012',
        'chat-ABCDEF12-3456-7890-ABCD-EF1234567890', // Uppercase should work
      ];

      validSessionIds.forEach(id => {
        expect(backendPattern.test(id)).toBe(true);
      });
    });

    it('/api/chat rejects plain UUID (old format)', async () => {
      const backendPattern = /^chat-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

      // Old format that should be rejected
      const invalidSessionIds = [
        'a1b2c3d4-e5f6-7890-abcd-ef1234567890', // Plain UUID
        '12345678-1234-1234-1234-123456789012',  // Plain UUID
        'session-a1b2c3d4-e5f6-7890-abcd-ef1234567890', // Wrong prefix
        'chat_a1b2c3d4-e5f6-7890-abcd-ef1234567890',   // Underscore instead of dash
      ];

      invalidSessionIds.forEach(id => {
        expect(backendPattern.test(id)).toBe(false);
      });
    });

    it('frontend-generated sessionId is accepted by /api/chat/archive', async () => {
      mockPut.mockResolvedValue({
        url: 'https://blob.vercel-storage.com/test',
        pathname: 'test',
      });

      const { POST } = await import('@/app/api/chat/archive/route');

      // Use a chat-prefixed session ID like frontend generates
      const request = new Request('http://localhost/api/chat/archive', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          sessionId: 'chat-a1b2c3d4-e5f6-7890-abcd-ef1234567890',
          sessionStartedAt: '2025-01-22T10:30:00.000Z',
          messages: [
            { id: '1', role: 'user', parts: [{ type: 'text', text: 'Hello' }] },
          ],
        }),
      });

      const response = await POST(request);
      const data = await response.json();

      expect(response.status).toBe(200);
      expect(data.success).toBe(true);
      expect(mockPut).toHaveBeenCalled();
    });

    it('plain UUID is rejected by /api/chat/archive', async () => {
      const consoleSpy = vi.spyOn(console, 'error').mockImplementation(() => {});
      vi.spyOn(console, 'log').mockImplementation(() => {});

      const { POST } = await import('@/app/api/chat/archive/route');

      // Use a plain UUID like the old format
      const request = new Request('http://localhost/api/chat/archive', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          sessionId: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890', // Plain UUID
          sessionStartedAt: '2025-01-22T10:30:00.000Z',
          messages: [
            { id: '1', role: 'user', parts: [{ type: 'text', text: 'Hello' }] },
          ],
        }),
      });

      const response = await POST(request);
      const data = await response.json();

      expect(response.status).toBe(400);
      expect(data.error).toContain('chat-prefixed');
      expect(mockPut).not.toHaveBeenCalled();

      consoleSpy.mockRestore();
    });
  });

  describe('session ID format documentation', () => {
    it('documents the expected session ID format', () => {
      // This test serves as documentation for the contract
      const format = {
        prefix: 'chat-',
        uuidVersion: 4,
        totalLength: 41, // 'chat-' (5) + UUID (36)
        pattern: 'chat-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
        regex: /^chat-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i,
        example: 'chat-a1b2c3d4-e5f6-7890-abcd-ef1234567890',
      };

      expect(format.regex.test(format.example)).toBe(true);
      expect(format.example.length).toBe(format.totalLength);
    });
  });
});
