/**
 * Integration tests for chat session ID contract between frontend and backend
 *
 * These tests verify that the session ID format generated by the frontend
 * (chat-storage.ts) is accepted by all backend endpoints.
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';

describe('chat session ID contract', () => {
  const SESSION_ID_PATTERN = /^chat-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

  beforeEach(() => {
    vi.clearAllMocks();
    vi.resetModules();
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  describe('frontend session ID generation', () => {
    it('initializeSession generates chat-prefixed UUID', async () => {
      // Mock localStorage
      const storage = new Map<string, string>();
      const localStorageMock = {
        getItem: vi.fn((key: string) => storage.get(key) ?? null),
        setItem: vi.fn((key: string, value: string) => storage.set(key, value)),
        removeItem: vi.fn((key: string) => storage.delete(key)),
      };
      Object.defineProperty(global, 'localStorage', { value: localStorageMock, writable: true });

      // Mock crypto.randomUUID
      const mockUUID = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890';
      Object.defineProperty(global, 'crypto', {
        value: { randomUUID: vi.fn().mockReturnValue(mockUUID) },
        writable: true,
      });

      const { initializeSession } = await import('@/lib/chat-storage');

      const sessionId = initializeSession();

      expect(sessionId).toBe(`chat-${mockUUID}`);
      expect(SESSION_ID_PATTERN.test(sessionId)).toBe(true);
    });
  });

  describe('backend validation accepts frontend format', () => {
    it('/api/chat validates chat-prefixed session ID correctly', async () => {
      // The regex used in /api/chat/route.ts
      const backendPattern = /^chat-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

      // Sample session IDs that frontend generates
      const validSessionIds = [
        'chat-a1b2c3d4-e5f6-7890-abcd-ef1234567890',
        'chat-12345678-1234-1234-1234-123456789012',
        'chat-ABCDEF12-3456-7890-ABCD-EF1234567890', // Uppercase should work
      ];

      validSessionIds.forEach(id => {
        expect(backendPattern.test(id)).toBe(true);
      });
    });

    it('/api/chat rejects plain UUID (old format)', async () => {
      const backendPattern = /^chat-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

      // Old format that should be rejected
      const invalidSessionIds = [
        'a1b2c3d4-e5f6-7890-abcd-ef1234567890', // Plain UUID
        '12345678-1234-1234-1234-123456789012',  // Plain UUID
        'session-a1b2c3d4-e5f6-7890-abcd-ef1234567890', // Wrong prefix
        'chat_a1b2c3d4-e5f6-7890-abcd-ef1234567890',   // Underscore instead of dash
      ];

      invalidSessionIds.forEach(id => {
        expect(backendPattern.test(id)).toBe(false);
      });
    });

    it('/api/chat/archive returns success as no-op (unified format handles persistence)', async () => {
      // Archive is now a no-op - live saves use unified format directly
      const { POST } = await import('@/app/api/chat/archive/route');

      const response = await POST();
      const data = await response.json();

      expect(response.status).toBe(200);
      expect(data.success).toBe(true);
    });
  });

  describe('session ID format documentation', () => {
    it('documents the expected session ID format', () => {
      // This test serves as documentation for the contract
      const format = {
        prefix: 'chat-',
        uuidVersion: 4,
        totalLength: 41, // 'chat-' (5) + UUID (36)
        pattern: 'chat-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
        regex: /^chat-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i,
        example: 'chat-a1b2c3d4-e5f6-7890-abcd-ef1234567890',
      };

      expect(format.regex.test(format.example)).toBe(true);
      expect(format.example.length).toBe(format.totalLength);
    });
  });
});
